Fix a bug in the trace statistics page
apache/skywalking-rocketbot-ui pull request #497
Opened 2021-05-26 10:00 UTC by constanine

![image](https://user-images.githubusercontent.com/7012545/119639396-260a5200-be4a-11eb-9bd6-f90cd8acc916.png)
…sorting, as the pictrue, I modify the judgment of the table head column,the column of 'Type' doesn't show the button

2021-05-26 10:01 UTC, constanine commented
> ![image](https://user-images.githubusercontent.com/7012545/119639396-260a5200-be4a-11eb-9bd6-f90cd8acc916.png)
> …so sorry, as the pictrue, I modify the judgment of the table head column,the column of 'Type' doesn't show the button

2021-05-26 12:40 UTC, Fine0830 requested changes

2021-05-26 12:40 UTC, Fine0830 commented on src/views/components/common/trace-chart-table/trace-container.vue
> +        <span class="r cp" @click="sortStatistics(item.key)" :key="componentKey" v-if="(item.key != 'endpointName') & (item.key != 'type')">
```suggestion
        <span class="r cp" @click="sortStatistics(item.key)" :key="componentKey" v-if="(item.key != 'endpointName') & (item.key != 'type')">
```
 <span class="r cp" @click="sortStatistics(item.key)" :key="componentKey" v-show="(item.key !== 'endpointName') & (item.key !== 'type')">

2021-05-27 05:38 UTC, Fine0830 approved these changes

2021-05-27 05:38 UTC, merged

2021-05-27 07:17 UTC, wu-sheng commented
This feature is still not synced to the main repo. Please sync that.